name: pokedex
description: "Desafio técnico"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  dio: ^5.9.0
  dartz: ^0.10.1
  flutter_modular: ^6.4.1
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/icon.png"
    background_color: "#000000"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/logo/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/icon.png"

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#000000"
  image: assets/logo/splash.png
  fullscreen: true
  android_12:
    color: "#000000"
    image: assets/logo/splash.png


flutter:

  uses-material-design: true
  assets:
    - assets/icons/pokemons/
    - assets/icons/others/
    - assets/icons/navbar/
    - assets/fonts/roboto/
    - assets/imgs/svg/
    - assets/imgs/png/
    - assets/logo/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-ExtraBold.ttf
          weight: 800
